apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcls-cu-inj-model-deployment
  namespace: lume-online-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lcls-cu-inj-model
  template:
    metadata:
      labels:
        app: lcls-cu-inj-model
    spec:
      containers:
      - name: lcls-cu-inj-model
        image: ghcr.io/slaclab/lcls-cu-inj-model:86de8b1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        env:
          - name: EPICS_CA_ADDR_LIST
            valueFrom:
              secretKeyRef:
                name: epics-secrets
                key: ca_addr_list
          - name: K2EG_IP
            valueFrom:
              secretKeyRef:
                name: k2eg-secrets
                key: kafka_broker_url
          - name: K2EG_TOPIC
            valueFrom:
              secretKeyRef:
                name: k2eg-secrets
                key: k2eg_cmd_topic
          - name: MODEL_VERSION
            value: "1"
